% load('Data\Injection2d_Weiyuan.mat');
clc;
IM_Plot2DField(xVec, yVec, tDay, CFS, ...
    'FieldName', '\DeltaCFS', ...
    'Unit', 'MPa', ...
    'Xi', xi, ...
    'Yi', yi, ...
    'TStartHour', t1, ...
    'ColormapName', 'RdBu', ...
    'SymmetricColor', true,'limit',[0 60],'SaveVideo',0);
%%
clc;
IM_Plot2DField(xVec, yVec, tDay, PorePressure, ...
    'FieldName', 'Pressure', ...
    'Unit', 'MPa', ...
    'Xi', xi, ...
    'Yi', yi, ...
    'TStartHour', t1, ...
    'ColormapName', 'RdBu', ...
    'SymmetricColor', true,'limit',[0 100],'SaveVideo',0);


